# Generated by Django 2.2.3 on 2019-08-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makaleler',
            name='makale_kategori',
            field=models.CharField(choices=[('bosanma', 'Boşanma'), ('nafaka', 'Nafaka'), ('velayet', 'Velayet'), ('aileicisiddet', 'Aile İçi Şiddet'), ('malpaylasimi', 'Mal Paylaşımı')], max_length=50, verbose_name='Makale Kategorisi'),
        ),
    ]
